### ISSUE TITLE
Bug: Geoserver password is not set

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode-k8s#102]
## Bug Description

If the geoserver password is changed via .Values.geoserver.secret.admin_password the password is not set. Instead it used the default password geoserver.

This is due to the missing `FORCE_REINIT` variable in `geoserver-env.yaml`. Further this variable is missing in `geonode-env.yaml` as well. This could be used instead of the not well implemented `IS_FIRST_START` variable. I guess in both cases (geoserver and geonode) this variable should always be true, to always apply changes to the values.yaml into the geonode installation.

## Reproduction Steps

best to provide your values.yaml, a brief description of your cluster and version of geonode-k8s here. 

##  Behavior

A description of what you expected to happen and what actually happened.

## Additional Information

Any additional information or context that may be helpful in resolving the bug.

**Comment by ridoo** [comment]
I think, setting Geoserver's password worked only for the very first start anyway. Current implementation even [got rid of setting the password](https://github.com/GeoNode/geonode/issues/11184) completely.

**Comment by mwallschlaeger** [comment]
ok looking forward to see this changes mentioned by @geohappy . Til then i tried to set `FORCE_REINIT = 'true'` on geoserver image. This is changing the password after each, restart of the pod. I will investigate same thing on the geonode side so that changing the geoserver-admin password via .Values is constant and properly working.
