### ISSUE TITLE
Feature: allow to use an existing configmap to replace nginx conf

### ISSUE THREAD

**Issue by AlexGacon** [zalf-rdm/geonode-k8s#112]
## Feature Description

To facilitate integration of a geonode instance with an external application, it would be great to have the possibility to add CORS origin info into NGINX configuration.

## Proposed Solution

- Add in values.yaml a new variable block `nginx.external_domain`.
- In charts/geonode/templates/nginx/nginx-conf.yaml, if extern_domain is enabled, add Access-Control-Allow-Origin directive in the configuration, targeting the configured domain.

## Additional Information

Any additional information or context that may be helpful in implementing the feature.

**Comment by AlexGacon** [comment]
I considered that the underlying file name is not changed but perhaps it is better to allow its configuration too.

**Comment by AlexGacon** [comment]
I can take care of it if it is ok with you.

**Comment by mwallschlaeger** [comment]
yes I can understand the requirement here. I  guess for most cases it would be enough to overwrite the configuration just partially. Like only the geoserver, or add addition configuration to a specific part. But sure for some use-cases also  using a  a whole self written config will be required.

If you create a PR i can definitely take a look at it.

**Comment by AlexGacon** [comment]
Ok. You will receive my PR when done.

**Comment by AlexGacon** [comment]
I updated the issue following the discussion in the proposed PR.
