### ISSUE TITLE
Task: Use release name in all K8s resource names

### ISSUE THREAD

**Issue by AlexGacon** [zalf-rdm/geonode-k8s#120]
## Task Description

Some resources don't have a name which includes the release name, making it difficult to find all the K8s resources related to a given deployment

## Additional Information

at least, there are geonode-secret and geoserver-secret.

**Comment by ridoo** [comment]
Perhaps this is a personal view and there may be reasons against it, but why not deploying everything in a dedicated namespace, e.g. using Helm's `--namespace` flag. IMO we could get rid of all ["release pod name" helper functions](https://github.com/zalf-rdm/geonode-k8s/blob/a9df2af7b46c44998406e4d1e06a9f706a5821b8/charts/geonode/templates/_helpers.tpl#L3-L18).

**Comment by mwallschlaeger** [comment]
yes @AlexGacon i agree to you. one helm Chart deployment should end up in a single namespace. and tighten together all objects of a deployment with a prefix to the name of the objects is common patten. therefore i would agree on giving all objects the release name as prefix.
