### ISSUE TITLE
Feature: configure external database

### ISSUE THREAD

**Issue by Mmoncadaisla** [zalf-rdm/geonode-k8s#123]
## Feature Description

It would be awesome if the PostgreSQL service was optional, being possible to connect to a compatible external database that complies with a minimal PostgreSQL and PostGIS versions.

## Proposed Solution

Ability to specify an external database in the `values.yaml` file, including the connection settings in an existent Secret.

## Additional Information

We're starting to review Geonode and the effort made here for deployment in k8s looks really promising. However, we already have a PostgreSQL operator [Cloud Native PG](https://cloudnative-pg.io/) and aim to keep using it.

**Comment by ridoo** [comment]
@Mmoncadaisla have a look here: https://github.com/zalf-rdm/geonode-k8s/blob/main/docs/external-database.md

Feel free to test and provide feedback!

**Comment by Mmoncadaisla** [comment]
@ridoo thank you so much for the quick reply and this is awesome, shame that I had not seen this section, I'll take a look and will share if I encounter any bumps on the road. 

We can close this one 😄
