### ISSUE TITLE
Task: Release 1.0.7

### ISSUE THREAD

**Issue by AlexGacon** [zalf-rdm/geonode-k8s#130]
## Task Description

Prepare code for the 1.0.7 release

## Additional Information

Any additional information or context that may be helpful in completing the task.

**Comment by AlexGacon** [comment]
@mwallschlaeger if it's ok for you, I can prepare the code base for the next release.

**Comment by mwallschlaeger** [comment]
yes thats fine to me. I will be back in office at the 19.01. Then I will continue the work on this repo. til then feel free to make a PR for a new release
