### ISSUE TITLE
Issue with running minikube deployment

### ISSUE THREAD

**Issue by deviirmr** [zalf-rdm/geonode-k8s#15]
Hi Zalf,
I like your helm chart geonode version.
I am trying to installing on minikube based on your suggestions 
![image](https://user-images.githubusercontent.com/10088434/196225097-7e496a46-7410-4ae6-b84a-681ec00fb504.png)

But I noticed the pod/geonode-geonode-0   is never been up, 
I also tried with 
![image](https://user-images.githubusercontent.com/10088434/196225462-b76aebf5-e001-44af-beb0-75850b6a87cd.png)

I am wondering is it the lastest geonode image zalf/geonode is tested or if not cloud you suggest which version should I try?
Thanks

**Comment by mwallschlaeger** [comment]
oh i just saw you issue today. I will test this out later today .
