### ISSUE TITLE
Feature: Allow to set Access-Control-Allow-Credentials to true in NGINX

### ISSUE THREAD

**Issue by AlexGacon** [zalf-rdm/geonode-k8s#155]
## Feature Description

For integration purpose of GeoNode into other systems, it would be great to allow in the NGINX configuration to setup Access-Control-Allow-Credentials to true instead of false.

## Proposed Solution

Add a new possible value in values.yaml with a default value to false and use it in the ConfigMap of NGINX.

## Additional Information

Any additional information or context that may be helpful in implementing the feature.

**Comment by AlexGacon** [comment]
@mwallschlaeger is it ok for you?

**Comment by mwallschlaeger** [comment]
yes sure, if you can make a PR we can add it to the next release 1.1.0
