### ISSUE TITLE
Task: Upgrade default versions for GeoServer and GeoServer_data

### ISSUE THREAD

**Issue by AlexGacon** [zalf-rdm/geonode-k8s#172]
## Task Description

Change the default docker tags of geoserver and geoserver_data in the values.yaml to use the last version published by GeoNode (2.24.2)

## Additional Information

Any additional information or context that may be helpful in completing the task.

**Comment by mwallschlaeger** [comment]
this should generally include geonode version 4.2.3

**Comment by mwallschlaeger** [comment]
closed with release 1.2.0
