### ISSUE TITLE
Task: release next version

### ISSUE THREAD

**Issue by AlexGacon** [zalf-rdm/geonode-k8s#205]
## Task Description

@mwallschlaeger, is it possible to have a new release of the chart, with the elements I added during summer? It will help us to remove custom code from our own helm charts.

## Additional Information

Any additional information or context that may be helpful in completing the task.

**Comment by mwallschlaeger** [comment]
i'm currently again on parantal leave til next Friday. but i'm gonna create a PR for this Tonight

**Comment by AlexGacon** [comment]
Done
