### ISSUE TITLE
configure CSW Harvesting

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode-k8s#24]
**Is your feature request related to a problem? Please describe. | Gehört diese neue Funktion zu einem bestehenden Problem? Welches?**

as described here: https://lists.osgeo.org/pipermail/geonode-users/2015-June/000533.html 

csw CATALOGUEs for harvesting can be defined in the settings.py. This must be configurable via values.yaml 

**Describe the solution you'd like | Beschreibe deinen Lösungsansatz**

implement a list of objects which get parsed into settings.py

**Comment by gannebamm** [comment]
What would you like to do here? Using GeoNetwork as a backend catalogue is currently untested and is currently not supported.

**Comment by mwallschlaeger** [comment]
> What would you like to do here? Using GeoNetwork as a backend catalogue is currently untested and is currently not supported.

mmh... I thought harvesting remote csw endpoints would be possible like:
```
CATALOGUE = {
    'default': {
         'ENGINE': 'geonode.catalogue.backends.geonetwork',
         'URL': 'http://gissrv.aes.hs-owl.de:8080/geonetwork/srv/en/csw',
         'USER': 'admin',
         'PASSWORD': 'AwesomePassword',
     }
}
```
in geonode settings.py. havent tested i yet. But if its is not implemented yet, ok.

**Comment by gannebamm** [comment]
That is what the original OP (old me :P) also thought. GeoNode can harvest WMS, ArcGIS MapServices and other GeoNode instances. You can take a look at the documentation here: https://docs.geonode.org/en/master/intermediate/harvesting/index.html#harvesting-resources-from-remote-services

It is possible to implement your own harvesters. GeoNode is a data portal and not a metadata catalogue; therefore, the harvesting of 'just' metadata resources is out of its purpose. A long time ago there was a discussion about that (https://github.com/GeoNode/geonode/issues/7057).

**Comment by mwallschlaeger** [comment]
this ist not accurate and up to date anymore. there for i close this.
