### ISSUE TITLE
Request to add a licence to this repository

### ISSUE THREAD

**Issue by Stinktopf** [zalf-rdm/geonode-k8s#26]
Hey @mwallschlaeger,
Would it be possible for you to add a licence to this repository? I am interested in using this Helm-Chart in the course of my bachelor thesis, but this is not possible without a suitable licence.

For me an **MIT license** would be ideal, but also the **GNU Affero General Public License v3.0** which you use in your other repositories should fit.

I would be very grateful if this could be arranged.

Best regards
Lucas Nickel

**Comment by mwallschlaeger** [comment]
closes with PR #29
