### ISSUE TITLE
Task: Remove ingress externalPort parameter

### ISSUE THREAD

**Issue by ridoo** [zalf-rdm/geonode-k8s#48]
## Task Description

`geonode.ingress.externalPort` had to be set as mandatory parameter. This was due to mistakenly usage as ingress target port. However, now it can be optional. 

## Additional Information

* Add a check for `nil` here:
  https://github.com/zalf-rdm/geonode-k8s/blob/bde327c89a35c8c137f4f620ebcc57c0de1c7a85/deployment/geonode/templates/_helpers.tpl#L85
* Check for Oauth config

**Comment by ridoo** [comment]
@mwallschlaeger can you confirm that `geonode.ingress.externalPort` even could be removed? I mean, would you run the whole GeoNode Application over a different port than `80` or `443`?

Even `GEONODE_LB_PORT` leaves the port empty when it is set `80` and `443`. For `PUBLIC_PORT` I did not find any reference which uses/reads it :shrug: . It seems to be a relict, and gets replaced by `GEONODE_LB_PORT` if set, anyways.

**Comment by mwallschlaeger** [comment]
yes i can confirm a static variable would be fine

**Comment by ridoo** [comment]
You mean it is ok to remove it completely from the setup, right?

**Comment by mwallschlaeger** [comment]
yes we can
