### ISSUE TITLE
Task: Add a configurable fixture template

### ISSUE THREAD

**Issue by ridoo** [zalf-rdm/geonode-k8s#49]
## Task Description

It would be nice to have a manifest which includes fixtures which are configurable  via `values.yaml`.

## Additional Information

* Use `{{ toYaml .Values.geonodeFixtures | nindent 2 }}` to include the fixtures.

Not sure about auto loading the fixtures via `python manage.py loaddata <yourfixturehere>`. For now this would have  be done manually. What is your opinion on this @mwallschlaeger ?

**Comment by mwallschlaeger** [comment]
I'm open to this idea. Using the current deployment will run into problems when using not vanilla geonode implementations. so make the helm chart aware of things like fixtures and so on is a plus. As geonode4.2 also targets a new init process for their django geonode container, this helm chart is open to initialize the deployment also apart from tasks.py. 

But for now i think defining fixtures inside the values.yaml could add a function call inside of tasks.py.
