### ISSUE TITLE
Use official geonode container image: geonode/geonode:latest-ubuntu-22.10

### ISSUE THREAD

**Issue by mwallschlaeger** [zalf-rdm/geonode-k8s#51]
## Task Description

use official geosolutions docker image in geonode-k8s as default image

**Comment by bradjones1** [comment]
Would this be possible as a drop-in replacement for `mwall2bitflow/geonode`? Not that I don't trust you, but I can't find the `Dockerfile` to audit this image at the moment?

**Comment by mwallschlaeger** [comment]
yes, the plan is to use the officially provided image from geonode. This just came into the docker deployment a few weeks ago. I haven't tested it yet in this deployment though but i guess it will just work out of the box

**Comment by ridoo** [comment]
Sidenote: For [the release 1.0.0](https://github.com/zalf-rdm/geonode-k8s/releases/tag/1.0.0) we released the Chart using `52north/geonode:4.1.2` until geosolutions publishes a stable base image.

**Comment by mwallschlaeger** [comment]
closed with #74
