### ISSUE TITLE
Bug: Image in Helm Chart refers to a non-final tag

### ISSUE THREAD

**Issue by ridoo** [zalf-rdm/geonode-k8s#66]
## Bug Description

For version `4.1.0` the Helm chart [refers to a non final image version `4.1.x`](https://github.com/zalf-rdm/geonode-k8s/blob/main/charts/geonode/values.yaml#L25). This is suboptimal, as it will not preserve using the same image in the future.

@mwallschlaeger what do you think? Shall we consider  to re-release the Chart?

**Comment by mwallschlaeger** [comment]
yes we should rethink the whole release and versioning part. Until yesterday i thought i would be a good idea to stick the version with the geonode versions. But after working on the artifacthub.io integration, I changed my mind. 

I would suggest to start with a new release 0.1 which targets the latest official geonode container and document this inside the release notes. and then from there on make new releases and test define which version can be run with which release. Maybe at some point a geonode-k8s release can also run multiple geonode version.

What do you think about that?

**Comment by ridoo** [comment]
What insights did make you change your mind regarding versioning?

The chart itself can have bugs, too, which have to fixed. I agree to decouple Chart version scheme from the GeoNode scheme. GeoNode version should be used [for the `appVersion` field](https://helm.sh/docs/topics/charts/#the-appversion-field).

**Comment by ridoo** [comment]
sounds good. What speaks against `1.0.0`? I think you made a good starting point already.

**Comment by ridoo** [comment]
@mwallschlaeger This issue can be closed IMO
